name: models
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1

dev_dependencies:
  build_runner: ^2.2.0
  lints: ^2.0.0
  test: ^1.16.0
