name: form_inputs
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  formz: ^0.4.1
  string_validator: ^0.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
